CC = g++
CFLAGS = -g -Wall

TARGET = main

all: $(TARGET)

$(TARGET): main.o Point3D.o
	$(CC) $(CFLAGS) $^ -o $(TARGET)

main.o: main.cpp main.h
	$(CC) $(CFLAGS) -c $< -o $@

Point3D.o: Point3D.cpp Point3D.h
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f *.o $(TARGET)

debug: $(TARGET)
	gdb $(TARGET)

.PHONY: all clean debug
